# Slicing and Dicing

In [1]:
import numpy as np

In [2]:
arreglo_once_cuadrado = np.arange(11)**2

In [3]:
arreglo_once_cuadrado

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [4]:
arreglo_once_cuadrado[0:4]

array([0, 1, 4, 9])

In [5]:
arreglo_once_cuadrado[-5:-1]

array([36, 49, 64, 81])

In [6]:
arreglo_once_cuadrado[::-2]

array([100,  64,  36,  16,   4,   0])

In [9]:
for numero in arreglo_once_cuadrado[::-2]:
    print(numero)

100
64
36
16
4
0
