# Reshaping

In [1]:
import numpy as np

In [2]:
paises_uno = ('Ecuador', 'USA', 'Cuba', 'Venezuela')

In [3]:
paises_dos = ('Brazil', 'China', 'Japon', 'Mexico')

In [4]:
arreglo_paises_2d = np.array([paises_uno, paises_dos])

In [5]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [7]:
#Ver numero de dimensiones de un arreglo, con el shape
arreglo_paises_2d.shape

(2, 4)

In [8]:
#Unir los datos de un arreglo de varias dimensiones en una sola dimension
arreglo_paises_2d.flatten()

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [11]:
arreglo_paises_2d.flatten().shape

(8,)

In [12]:
#Para reinventir un arreglo plano a uno con varias dimensiones
arreglo_paises_2d.flatten().reshape(2,2,2)

array([[['Ecuador', 'USA'],
        ['Cuba', 'Venezuela']],

       [['Brazil', 'China'],
        ['Japon', 'Mexico']]], dtype='<U9')

In [13]:
arreglo_paises_2d.flatten().reshape(4, -1) #Lo que logre llenar

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brazil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [14]:
arreglo_paises_2d.flatten()

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [16]:
#Transpuesta
arreglo_paises_2d.T

array([['Ecuador', 'Brazil'],
       ['USA', 'China'],
       ['Cuba', 'Japon'],
       ['Venezuela', 'Mexico']], dtype='<U9')

In [17]:
arreglo_paises = arreglo_paises_2d.flatten()

In [18]:
arreglo_paises

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brazil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [19]:
np.split(arreglo_paises, 2)

[array(['Ecuador', 'USA', 'Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brazil', 'China', 'Japon', 'Mexico'], dtype='<U9')]

In [20]:
np.split(arreglo_paises, 4)

[array(['Ecuador', 'USA'], dtype='<U9'),
 array(['Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brazil', 'China'], dtype='<U9'),
 array(['Japon', 'Mexico'], dtype='<U9')]

In [24]:
arreglo = np.arange(12)

In [25]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.split(arreglo, [1,2,5,7,8,10]) #Indice donde se cortara el arreglo

[array([0]),
 array([1]),
 array([2, 3, 4]),
 array([5, 6]),
 array([7]),
 array([8, 9]),
 array([10, 11])]

In [34]:
np.hsplit(arreglo_paises_2d, 2)

[array([['Ecuador', 'USA'],
        ['Brazil', 'China']], dtype='<U9'), array([['Cuba', 'Venezuela'],
        ['Japon', 'Mexico']], dtype='<U9')]

In [35]:
np.vsplit(arreglo_paises_2d, 2)

[array([['Ecuador', 'USA', 'Cuba', 'Venezuela']], dtype='<U9'),
 array([['Brazil', 'China', 'Japon', 'Mexico']], dtype='<U9')]

In [36]:
x1, x2, x3 = [1,2,3]

In [38]:
x1

1

In [40]:
x1 = x2 = x3 = 1

In [42]:
x2

1

In [43]:
x1 = x1 + 1 

In [44]:
x1

2

In [45]:
x2

1