In [1]:
import numpy as np

In [7]:
numeros = np.arange(11)*2

In [8]:
numeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
indices = [2,5,7]

In [10]:
numeros[indices]

array([ 4, 10, 14])

In [11]:
# rutas

arreglo_frutas = np.array([
    ['Piña', 'Manzana', 'Pera', 'Melon'],
    ['Pera', 'Uva', 'Naranja', 'Papaya'],
    ['Frutilla', 'Platano', 'Grandadilla', '']
])

In [30]:
arreglo_frutas.shape

(3, 4)

In [31]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [32]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])

In [33]:
arreglo_columnas

array([[1, 3],
       [1, 2],
       [0, 2]])

In [34]:
arreglo_frutas[arreglo_filas, arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Grandadilla']], dtype='<U11')

In [68]:
arreglo_frutas

#arreglo_frutas.shape

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Grandadilla', 'Sandia']], dtype='<U11')

In [36]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

arreglo_columnas = np.array([
    [2,3],
    [2,3],
    [2,3],
])

arreglo_frutas[arreglo_filas, arreglo_columnas]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Grandadilla', 'Sandia']], dtype='<U11')

In [93]:
arreglo_frutas_2 = np.array([
    ['Piña', 'Manzana', 'Pera', 'Melon'],
    ['Higo', 'Uva', 'Naranja', 'Papaya'],
    ['Frutilla', 'Platano', 'Grandadilla', 'Achotillo'],
    ['Mango', 'Uvilla', 'Arandanos', 'Frambuesa'],
    ['Mandarina', 'Chirimoya', 'Guanabana', 'Kiwi'],
    ['Cereza', 'Ciruela', 'Níspero', 'Nuez']
])

In [94]:
arreglo_frutas_2.flatten().shape

(24,)

In [95]:
arreglo_frutas_2.shape = 4,3,2

In [96]:
arreglo_frutas_2

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Higo', 'Uva']],

       [['Naranja', 'Papaya'],
        ['Frutilla', 'Platano'],
        ['Grandadilla', 'Achotillo']],

       [['Mango', 'Uvilla'],
        ['Arandanos', 'Frambuesa'],
        ['Mandarina', 'Chirimoya']],

       [['Guanabana', 'Kiwi'],
        ['Cereza', 'Ciruela'],
        ['Níspero', 'Nuez']]], dtype='<U11')

In [138]:
arreglo_filas = np.array([
    [0,2,2],
])

arreglo_columnas = np.array([
    [0,1,1],
])

arreglo_profundidad = np.array([
    [0,3,1],
])

In [139]:
arreglo_frutas_2[arreglo_profundidad, arreglo_filas, arreglo_columnas]
# arreglo_frutas_2[1, 1, 1]

array([['Piña', 'Nuez', 'Achotillo']], dtype='<U11')

In [148]:
arreglo_filas = np.array([
    [
        [0,0],
        [1,1]
    ],
    [
        [2,1],
        [0,1]
    ],
])

arreglo_columnas = np.array([
    [
        [0,1],
        [0,1]
    ],
    [
        [1,0],
        [0,1]
    ],
])

arreglo_profundidad = np.array([
    [
        [0,0],
        [0,0]
    ],
    [
        [3,3],
        [3,3]
    ],
])

In [149]:
arreglo_frutas_2[arreglo_profundidad, arreglo_filas, arreglo_columnas]

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon']],

       [['Nuez', 'Cereza'],
        ['Guanabana', 'Ciruela']]], dtype='<U11')

In [150]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Grandadilla', 'Sandia']], dtype='<U11')

In [151]:
arreglo_frutas_1d = arreglo_frutas.flatten()

In [152]:
arreglo_frutas_1d

array(['Piña', 'Manzana', 'Pera', 'Melon', 'Pera', 'Uva', 'Naranja',
       'Papaya', 'Frutilla', 'Platano', 'Grandadilla', 'Sandia'],
      dtype='<U11')

In [193]:
for fruta in arreglo_frutas_1d:
    for x in fruta[0:1:]:
        print(x)
        if(x == 'P'):
            frutas.push(fruta)
        

P


NameError: name 'frutas' is not defined