In [1]:
import numpy as np

In [2]:
numeros = np.arange(11)*2

In [3]:
numeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
indices = [2,5,7]

In [5]:
numeros[indices]

array([ 4, 10, 14])

In [6]:
# rutas

arreglo_frutas = np.array([
    ['Piña', 'Manzana', 'Pera', 'Melon'],
    ['Pera', 'Uva', 'Naranja', 'Papaya'],
    ['Frutilla', 'Platano', 'Grandadilla', 'Achotillo']
])

In [7]:
arreglo_frutas.shape

(3, 4)

In [8]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [9]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])

In [10]:
arreglo_columnas

array([[1, 3],
       [1, 2],
       [0, 2]])

In [11]:
arreglo_frutas[arreglo_filas, arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Grandadilla']], dtype='<U11')

In [12]:
arreglo_frutas

#arreglo_frutas.shape

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Grandadilla', 'Achotillo']], dtype='<U11')

In [13]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

arreglo_columnas = np.array([
    [2,3],
    [2,3],
    [2,3],
])

arreglo_frutas[arreglo_filas, arreglo_columnas]

array([['Pera', 'Melon'],
       ['Naranja', 'Papaya'],
       ['Grandadilla', 'Achotillo']], dtype='<U11')

In [14]:
arreglo_frutas_2 = np.array([
    ['Piña', 'Manzana', 'Pera', 'Melon'],
    ['Higo', 'Uva', 'Naranja', 'Papaya'],
    ['Frutilla', 'Platano', 'Grandadilla', 'Achotillo'],
    ['Mango', 'Uvilla', 'Arandanos', 'Frambuesa'],
    ['Mandarina', 'Chirimoya', 'Guanabana', 'Kiwi'],
    ['Cereza', 'Ciruela', 'Níspero', 'Nuez']
])

In [15]:
arreglo_frutas_2.flatten().shape

(24,)

In [16]:
arreglo_frutas_2.shape = 4,3,2

In [17]:
arreglo_frutas_2

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Higo', 'Uva']],

       [['Naranja', 'Papaya'],
        ['Frutilla', 'Platano'],
        ['Grandadilla', 'Achotillo']],

       [['Mango', 'Uvilla'],
        ['Arandanos', 'Frambuesa'],
        ['Mandarina', 'Chirimoya']],

       [['Guanabana', 'Kiwi'],
        ['Cereza', 'Ciruela'],
        ['Níspero', 'Nuez']]], dtype='<U11')

In [18]:
arreglo_filas = np.array([
    [0,2,2],
])

arreglo_columnas = np.array([
    [0,1,1],
])

arreglo_profundidad = np.array([
    [0,3,1],
])

In [19]:
arreglo_frutas_2[arreglo_profundidad, arreglo_filas, arreglo_columnas]
# arreglo_frutas_2[1, 1, 1]

array([['Piña', 'Nuez', 'Achotillo']], dtype='<U11')

In [20]:
arreglo_filas = np.array([
    [
        [0,0],
        [1,1],
        [2,2]
    ],
    [
        [0,0],
        [1,1],
        [2,2]
    ],
    [
        [0,0],
        [1,1],
        [2,2]
    ],
    [
        [0,0],
        [1,1],
        [2,2]
    ]
])

arreglo_columnas = np.array([
    [
        [0,1],
        [0,1],
        [0,1]
    ],
    [
        [0,1],
        [0,1],
        [0,1]
    ],
    [
        [0,1],
        [0,1],
        [0,1]
    ],
    [
        [0,1],
        [0,1],
        [0,1]
    ]
])

arreglo_profundidad = np.array([
    [
        [0,0],
        [0,0],
        [0,0],
    ],
    [
        [1,1],
        [1,1],
        [1,1]
    ],
    [
        [2,2],
        [2,2],
        [2,2]   
    ],
    [
        [3,3],
        [3,3],
        [3,3]
    ]
])

In [21]:
arreglo_frutas_2[arreglo_profundidad, arreglo_filas, arreglo_columnas]

array([[['Piña', 'Manzana'],
        ['Pera', 'Melon'],
        ['Higo', 'Uva']],

       [['Naranja', 'Papaya'],
        ['Frutilla', 'Platano'],
        ['Grandadilla', 'Achotillo']],

       [['Mango', 'Uvilla'],
        ['Arandanos', 'Frambuesa'],
        ['Mandarina', 'Chirimoya']],

       [['Guanabana', 'Kiwi'],
        ['Cereza', 'Ciruela'],
        ['Níspero', 'Nuez']]], dtype='<U11')

In [22]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Grandadilla', 'Achotillo']], dtype='<U11')

In [23]:
arreglo_frutas_1d = arreglo_frutas.flatten()

In [24]:
arreglo_frutas_1d

array(['Piña', 'Manzana', 'Pera', 'Melon', 'Pera', 'Uva', 'Naranja',
       'Papaya', 'Frutilla', 'Platano', 'Grandadilla', 'Achotillo'],
      dtype='<U11')

In [25]:
for fruta in arreglo_frutas_1d:
    if 'P' in fruta:
        print(fruta)

Piña
Pera
Pera
Papaya
Platano
