# Numpy

In [2]:
# pip install numpy
import numpy as np

In [3]:
# creamos un arreglo

arreglos = np.array([1,2,3])

In [4]:
arreglos

array([1, 2, 3])

In [5]:
# arreglo tipo array de ceros
np.zeros(4) 

array([0., 0., 0., 0.])

In [7]:
# arreglo tipo matriz
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# podemos crear igual pero de 1's (tupla)
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# podemos crear igual pero de 1's (tupla)
array_ejem = np.ones((2,3))
array_ejem
array_ejem*2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [18]:
# crear una matriz reservando espacio de memoria
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# creacion de una matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Definir una matriz con valores del 1 al 5
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
# crear un vector con un valor inicial, final, y el salto que debe dar.
np.arange(2, 9, 0.75) 

array([2.  , 2.75, 3.5 , 4.25, 5.  , 5.75, 6.5 , 7.25, 8.  , 8.75])

In [23]:
# transformar en un vector de dos dimensiones
np.arange(10).reshape(5,2) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
# transformar en un vector de tres dimensiones
np.arange(18).reshape(3,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [25]:
# generar un numero randomico entre 3, 20
np.random.randint(3,20)

3

In [26]:
# generar una matriz randomica de 2x3, con valores randomicos entre 5 y 17
np.random.randint(5,17, size=(2,3))

array([[15, 10, 12],
       [ 8, 16,  5]])

In [29]:
# generar una matriz randomica de 2x2, con valores randomicos enteros entre 1 y 5
a = np.random.randint(1,5, size=(2,2))

In [30]:
a

array([[2, 4],
       [4, 3]])

In [31]:
b = np.random.randint(1,5, size=(2,2))

In [32]:
b

array([[2, 3],
       [2, 4]])

In [41]:
# operaciones con matrices
print('suma', a+b)
print('resta', a-b)
print('multiplicacion', a*b)
print('division', a/b)
print('residuo', a%b)

suma [[4 7]
 [6 7]]
resta [[ 0  1]
 [ 2 -1]]
multiplicacion [[ 4 12]
 [ 8 12]]
division [[1.         1.33333333]
 [2.         0.75      ]]
residuo [[0 1]
 [0 3]]


In [42]:
# producto cartesinO
a.dot(b)

array([[12, 22],
       [14, 24]])

In [43]:
# VERIFICA si los datos de una matriz son mayores a 2
a > 2

array([[False,  True],
       [ True,  True]])

In [45]:
# multiplico una matriz
a * 2

array([[4, 8],
       [8, 6]])

In [47]:
# valor minimo de una matriz
a.min()

2

In [48]:
# valor maximo de una matriz
a.max()

4

In [49]:
# sacar el valor medio de una matriz
np.median(a)

3.5

In [50]:
# funcion de arcsin de uno
np.arcsin(1)

1.5707963267948966

In [51]:
np.std(a) 

0.82915619758885

In [54]:
# varianza
np.var(a) 

0.6875

In [57]:
# imprime un vector quitando el ultimo elemento 
a.reshape(4)[:-1]

array([2, 4, 4])

In [58]:
# imprimir valores
for num in a.reshape(4):
    print(num)

2
4
4
3


In [59]:
A = np.array([[1,2],[3,4],[5,6]])

In [60]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
for num in np.nditer(A, order='F'):
    print(num)

1
3
5
2
4
6


In [62]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

In [63]:
# numero de elementos
A.size

6

In [67]:
# dimension de la matriz
A.shape 

(3, 2)

In [68]:
# me da la transpuesta
A.T 

array([[1, 3, 5],
       [2, 4, 6]])

In [69]:
# crear arreglo con 12 elementos
arreglo_doce = np.arange(1, 13)

In [70]:
arreglo_doce

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
# dividir un arreglo en tres partes
# partir el arreglo en el numero que pueda ser divisible
np.split(arreglo_doce, 3) 

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [72]:
np.split(arreglo_doce, [2,3,4,10])

[array([1, 2]),
 array([3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10]),
 array([11, 12])]